FROM devopsdockeruh/simple-web-service
# Use /usr/src/app as our workdir. The following instructions will be executed in this location.
WORKDIR /usr/src/app

# When running Docker run the command will be ./hello.sh
CMD server
